<a href="https://colab.research.google.com/github/vidjaydas/DS_Assignments/blob/main/Probability_of_MPG_cars_Q20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
data = pd.read_csv('/content/Cars.csv')

In [ ]:
data.head()

HP        MPG  VOL          SP         WT
0  49  53.700681   89  104.185353  28.762059
1  55  50.013401   92  105.461264  30.466833
2  55  50.013401   92  105.461264  30.193597
3  70  45.696322   92  113.461264  30.632114
4  53  50.504232   92  104.461264  29.889149

In [ ]:
data.shape

(81, 5)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   HP      81 non-null     int64  
 1   MPG     81 non-null     float64
 2   VOL     81 non-null     int64  
 3   SP      81 non-null     float64
 4   WT      81 non-null     float64
dtypes: float64(3), int64(2)
memory usage: 3.3 KB


In [ ]:
mpg = data[['MPG']]

In [ ]:
mpg.describe()

MPG
count  81.000000
mean   34.422076
std     9.131445
min    12.101263
25%    27.856252
50%    35.152727
75%    39.531633
max    53.700681

In [ ]:
mean = mpg.mean()

In [ ]:
std = mpg.std()

In [ ]:
mean

MPG    34.422076
dtype: float64

In [ ]:
1-stats.norm.cdf(38, loc=mean, scale=std)    # Greater than 38

array([0.34759393])

In [ ]:
stats.norm.cdf(40, loc=mean, scale=std)      # Less than 40

array([0.72934988])

In [ ]:
greater20 = stats.norm.cdf(20, loc=mean, scale=std)
greater20

array([0.05712378])

In [ ]:
less50 = stats.norm.cdf(50, loc=mean, scale=std)

In [ ]:
print(less50-greater20)

[0.89886892]
